import argparse
import os
import shutil
import sys
from pyutils.executor import Executor
import pyutils.fsext as fs
import pyutils.simplelogger as logger

sub_project = {
    "hog": [
        "-q 01",
        "-q 02 -u",
        "-q 02",
        "-q 03 -u",
        "-q 03",
        "-q 04 -u",
        "-q 04",
        "-q 05 -u",
        "-q 05",
        "-q 06 -u",
        "-q 06",
        "-q 07",
        "-q 08 -u",
        "-q 08",
        "-q 09 -u",
        "-q 09",
        "-q 10 -u",
        "-q 10",
        "-q 11 -u",
        "-q 11",
        "-q 12",
    ],
    "hw01": [""],
    "hw02": ["-q product", "-q factorial", "-q make_adder"],
    "hw03": [
        "-q has_seven",
        "-q summation",
        "-q accumulate",
        "-q summation_using_accumulate",
        "-q product_using_accumulate",
        "-q filtered_accumulate",
        "-q make_repeater",
        "-q church_to_int",
        "-q add_church",
        "-q mul_church",
        "-q pow_church",
    ],
    "hw04": [
        "-q taxicab",
        "-q squares",
        "-q g",
        "-q g_iter",
        "-q pingpong",
        "-q count_change",
        "-q make_anonymous_factorial",
    ],
    "lab00": [""],
    "lab01": [""],
    "lab02": [
        "-q lambda -u",
        "-q hof -u",
        "-q lambda_curry2",
        "-q composite_identity",
        "-q count_cond",
        "-q cycle",
    ],
    "lab03": [
        "-q gcd",
        "-q hailstone",
        "-q call_expressions -u",
        "-q cycle",
        "-q is_palindrome",
        "-q skip_mul_ok -u",
        "-q skip_mul",
        "-q is_prime",
        "-q interleaved_sum",
        "-q ten_pairs",
    ],
    "lab04": [
        "-q indexing -u",
        "-q lists -u",
        "-q if_this_not_that",
        "-q distance",
        "-q closer_city",
        "-q distance -q closer_city",
        "-q flatten",
        "-q merge",
        "-q create_row",
        "-q create_board",
        "-q replace_elem",
        "-q get_piece -q put_piece",
        "-q make_move",
        "-q print_board",
        "-q check_win_row",
        "-q check_win_column",
        "-q check_win",
    ],
    "maps": [
        "-q 00 -u",
        "-q 00",
        "-q 01 -u",
        "-q 01",
        "-q 02 -u",
        "-q 02",
        "-q 03 -u",
        "-q 03",
        "-q 04 -u",
        "-q 04",
        "-q 05 -u",
        "-q 05",
        "-q 06 -u",
        "-q 06",
        "-q 07 -u",
        "-q 07",
        "-q 08 -u",
        "-q 08",
        "-q 09 -u",
        "-q 09",
        "-q 10 -u",
        "-q 10",
    ],
    "lab05": ["-q dicts -u",
              "-q map",
              "-q filter",
              "-q reduce",
              "-q acorn_finder",
              "-q replace_leaf",
              "-q build_successors_table",
              "-q construct_sent",
              "-q prune_leaves",
              "-q sprout_leaves",
              "-q add_trees"],
    "hw05": ["-q replace_leaf",
             "-q move_stack",
             "-q total_weight",
             "-q balanced",
             "-q Account",
             "-q FreeChecking",
             "-q make_counter",
             "-q make_fib",
             "-q make_withdraw",
             "-q make_joint"
             "-q interval -u",
             "-q interval",
             "-q mul_interval -u",
             "-q mul_interval",
             "-q sub_interval -u",
             "-q sub_interval",
             "-q div_interval -u",
             "-q div_interval",
             "-q check_par",
             "-q quadratic"],
    "lab06": ["-q car -u",
              "-q food_truck -u",
              "-q me",
              "-q Player.go_to",
              "-q vending_machine",
              "-q Player.talk_to",
              "-q Player.take",
              "-q Player.unlock"],
    "ants": ["-q 00 -u",
             "-q 01 -u",
             "-q 01",
             "-q 02 -u",
             "-q 02",
             "-q 03 -u",
             "-q 03",
             "-q 04 -u",
             "-q 04",
             "-q 05 -u",
             "-q 05",
             "-q 06 -u",
             "-q 06",
             "-q 07 -u",
             "-q 07",
             "-q 08 -u",
             "-q 08",
             "-q 09 -u",
             "-q 09",
             "-q 10 -u",
             "-q 10",
             "-q 11 -u",
             "-q 11",
             "-q 12 -u",
             "-q 12",
             "-q 13 -u",
             "-q 13",
             "-q EC -u",
             "-q EC"],
    "hw06": ["-q Fib",
             "-q VendingMachine"],
    "lab07": ["-q link -u",
              "-q trees -u",
              "-q link_to_list",
              "-q store_digits",
              "-q cumulative_sum",
              "-q remove_all",
              "-q deep_map_mut",
              "-q has_cycle",
              "-q has_cycle_constant",
              "-q reverse_other"],
    "hw07": ["-q digits",
             "-q MissManners"],
    "lab08": ["-q deep_len",
              "-q growth -u",
              "-q foobar -u",
              "-q attributes -u",
              "-q Keyboard",
              "-q make_advanced_counter_maker",
              "-q trade",
              "-q make_to_string",
              "-q tree_map",
              "-q long_paths",
              "-q zap -u",
              "-q boom -u"],
    "lab09": ["-q wwsd-lists -u",
              "-q over-or-under -u",
              "-q over-or-under",
              "-q filter -u",
              "-q filter",
              "-q make-adder -u",
              "-q make-adder",
              "-q make-list -u",
              "-q composed -u",
              "-q composed",
              "-q remove -u",
              "-q remove",
              "-q gcd -u",
              "-q gcd",
              "-q no-repeats -u",
              "-q no-repeats",
              "-q substitute -u",
              "-q substitute",
              "-q sub-all -u",
              "-q sub-all"],
    "hw09": ["-q how-many-dots -u",
             "-q how-many-dots",
             "-q derive-sum -u",
             "-q derive-sum",
             "-q derive-product -u",
             "-q derive-product",
             "-q make-exp -u",
             "-q make-exp",
             "-q derive-exp -u",
             "-q derive-exp",
             ],
    "lab10": ["-q prologue_reader -u",
              "-q prologue_expr -u",
              "-q Name.eval",
              "-q CallExpr.eval",
              "-q LambdaFunction.apply"],
    "scheme": ["-q 01 -u",
               "-q 01",
               "-q 02 -u",
               "-q 02",
               "-q eval_apply -u",
               "-q 03 -u",
               "-q 03",
               "-q 04 -u",
               "-q 04",
               "-q 05 -u",
               "-q 05",
               "-q 06 -u",
               "-q 06",
               "-q 07 -u",
               "-q 07",
               "-q 08 -u",
               "-q 08",
               "-q 09 -u",
               "-q 09",
               "-q 10 -u",
               "-q 10",
               "-q 11 -u",
               "-q 11",
               "-q 12 -u",
               "-q 12"]
}

if __name__ == "__main__":
    myargparse = argparse.ArgumentParser()
    myargparse.add_argument(type=str, help='The sub project name.', dest='proj', default=None)
    myargparse.add_argument('--all', help='Run all sub project\'s job.', default=False, action='store_true')
    parsed_args = myargparse.parse_args()
    proj = parsed_args.proj
    if proj is None:
        print("Please input a specific category.(e.g. hw01)")
        sys.exit(-1)
    if proj not in sub_project.keys():
        logger.error(f"{proj} not in {sub_project.keys()}")
        exit()
    current_dir = os.path.dirname(__file__)
    proj_dir = os.path.join(current_dir, proj)
    if not os.path.exists(os.path.join(proj_dir, "ok")):
        ok_exe_pattern = os.path.join(current_dir, "**/ok")
        ok_exe = fs.search(ok_exe_pattern)
        assert ok_exe
        shutil.copyfile(ok_exe, os.path.join(proj_dir, "ok"))
    e = Executor()
    questions = sub_project[proj]
    for q in questions:
        if parsed_args.all or q == questions[-1]:
            logger.info(f"current action : {q}")
            e.execute_file(
                sys.executable, ["ok", "--local", q], work_dir=proj_dir, use_direct_stdout=True
            )
